version: '3'
services:

  mongo:
    image: mongo:latest
    ports:
      - "0.0.0.0:27017:27017"
    volumes:
      - mongo_data:/data/db

  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      - MONGO_URL=mongodb://mongo:27017/challenge
    depends_on:
      - mongo
    command: >
      bash -c "
        echo 'Waiting for MongoDB to start...'
        sleep 10
        npm start
      "

volumes:
  mongo_data: